CREATE OR REPLACE DATABASE TCG;

CREATE TABLE CARDS(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	CARD_NAME VARCHAR (255) UNIQUE,
	CARD_TYPE VARCHAR (255),
	CARD_IMG VARCHAR (255) UNIQUE,
	CARD_EFF VARCHAR (255),
	CARD_ATK SMALLINT,
	CARD_DEFENSE SMALLINT,
	PRICE NUMERIC(7,2)
) ENGINE = INNODB;

CREATE TABLE EXPANSION(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	EXPANSION_NAME VARCHAR (255) UNIQUE,
	EXPANSION_DATE DATE,
	EXPANSION_PRICE NUMERIC(7,2),
	STOCK INT
) ENGINE = INNODB;

CREATE TABLE EXPANSION_CARDS(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	CARD_ID INT NOT NULL,
	EXPANSION_ID INT NOT NULL,
	CONSTRAINT FK_CARD_ID FOREIGN KEY (CARD_ID)
    REFERENCES CARDS(ID),
    CONSTRAINT FK_EXPANSION_ID FOREIGN KEY (EXPANSION_ID)
    REFERENCES EXPANSION(ID)
) ENGINE = INNODB;